[package]
name = "chkdraft-bindings"
version = "0.1.0"
edition = "2021"
description = "Rust bindings for Chkdraft map rendering library"

[dependencies]

[dev-dependencies]
reqwest = { version = "*", features = ["blocking"] }

[build-dependencies]
bindgen = "0.70"
cc = "1.0"
